const technologies = [
  { name: "React", years: 5, proficiency: 5 },
  { name: "Next", years: 2, proficiency: 4 },
  { name: "Typescript", years: 6, proficiency: 5 },
  { name: "Javascript", years: 8, proficiency: 5 },
  { name: "HTML", years: 8, proficiency: 5 },
  { name: "CSS", years: 8, proficiency: 5 },
  { name: "Storybook", years: 2, proficiency: 4 },
  { name: "Styled Components", years: 1, proficiency: 4 },
  { name: "TailwindCSS", proficiency: 5 },
  { name: "CSS Modules", proficiency: 5 },
  { name: "Sass", proficiency: 5 },
  { name: "Angular", proficiency: 3 },
  { name: "Astro", proficiency: 3 },
  { name: "MaterialUI", proficiency: 5 },
  { name: "React Query" },
  { name: "React Native", years: 1, proficiency: 3 },
  { name: "Unit testing" },
  { name: "Responsiveness", years: 6, proficiency: 5 },
  { name: "Accessibility", years: 4, proficiency: 5 },
  { name: "Remix", years: 1, proficiency: 4 },
  { name: "Firebase", proficiency: 3 },
  { name: "CRA" },
  { name: "Parcel" },
  { name: "jQuery" },
  { name: "MongoDB", years: 1, proficiency: 3 },
  { name: "Prisma", proficiency: 3 },
  { name: "Python", proficiency: 4 },
  { name: "Cypress", proficiency: 2 },
  { name: "Elixir", years: 1, proficiency: 2 },
  { name: "Django", years: 1, proficiency: 2 },
];

export default technologies;
