name: test
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.6.0'
      - run: yarn install
      - run: yarn build
      - run: yarn prettier
      - run: yarn lint
      - run: yarn test
